In [16]:
# import numpy and pandas, then "abbreviate" them

%pip install numpy
%pip install pandas
import numpy as np
import pandas as pd

Requirement already satisfied: numpy in /opt/miniconda3/lib/python3.14/site-packages (2.5.3)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in /opt/miniconda3/lib/python3.14/site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in /opt/miniconda3/lib/python3.14/site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/miniconda3/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/miniconda3/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:
# make an array of numbers 0 to 100 (exclusive)
random_list = np.arange(stop=100)
# print the random_list variable
print(random_list)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

In [18]:
#doing mathematical operations on our list
#want list to start at 1
#addd 1 to each
random_list = random_list + 1
print(random_list)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

In [19]:
print(np.log(random_list))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176
 2.94443898 2.99573227 3.04452244 3.09104245 3.13549422 3.17805383
 3.21887582 3.25809654 3.29583687 3.33220451 3.36729583 3.40119738
 3.4339872  3.4657359  3.49650756 3.52636052 3.55534806 3.58351894
 3.61091791 3.63758616 3.66356165 3.68887945 3.71357207 3.73766962
 3.76120012 3.78418963 3.80666249 3.8286414  3.8501476  3.87120101
 3.8918203  3.91202301 3.93182563 3.95124372 3.97029191 3.98898405
 4.00733319 4.02535169 4.04305127 4.06044301 4.07753744 4.09434456
 4.11087386 4.12713439 4.14313473 4.15888308 4.17438727 4.18965474
 4.20469262 4.21950771 4.2341065  4.24849524 4.26267988 4.27666612
 4.29045944 4.30406509 4.31748811 4.33073334 4.34380542 4.35670883
 4.36944785 4.38202663 4.39444915 4.40671925 4.41884061 4.4308168
 4.44265126 4.4543473  4.46590812 4.47733681 4.48863637 4.49980967
 4.51085951 4.52178858 4.53259949 4.54329478 4.55387689 4.56434819
 4.57471098 4.58496748 4.59511985 4.60517019]

In [20]:
#boolean indexing can also be performed using a boolean array
#index array allows us to see where all the odds are
print(random_list % 2 == 0)

even_list_2 = random_list[random_list % 2 == 0]
print(even_list_2)

[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True False  True False  True
 False  True False  True]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]

In [21]:
even_list_3 = np.array([])

for i in range(1, 101):
    if i % 2 == 0:
        even_list_3 = np.append(arr = even_list_3, values = i)

print(even_list_3)

[  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.  24.  26.  28.
  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.  52.  54.  56.
  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.  80.  82.  84.
  86.  88.  90.  92.  94.  96.  98. 100.]

In [22]:
#make an array of numbers 0 to 200 exlclusive
big_list = np.arange(200)
even_list_A = [2*x for x in big_list if x <= 50] #saves many lines of code
even_list_A = np.array(even_list_A)
print(even_list_A)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]

In [28]:
#A3
test_list = np.array([ -99.52287875, -100.        ,  -99.39794001, -100.        ,
        -99.30103   ,  -99.04575749,  -99.69897   ,  -99.22184875,
        -99.30103   ,  -99.52287875,  -99.30103   ,  -99.09691001,
        -99.04575749,  -99.15490196,  -99.04575749,  -99.52287875,
        -99.69897   ,  -99.52287875,  -99.09691001,  -99.39794001,
        -99.22184875,  -99.69897   ,  -99.22184875,  -99.39794001])

In [29]:
test_list = test_list + 100
test_list = np.power(10, test_list)
test_list = np.round(test_list)
print(test_list)

[3. 1. 4. 1. 5. 9. 2. 6. 5. 3. 5. 8. 9. 7. 9. 3. 2. 3. 8. 4. 6. 2. 6. 4.]

In [31]:
gapminder = pd.read_csv("data/gapminder.csv")
gapminder

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [ ]:
print(gapminder.iloc[1])
#iloc gives indecies

country      Afghanistan
continent           Asia
year                1957
lifeExp           30.332
pop              9240934
gdpPercap      820.85303
Name: 1, dtype: object

In [33]:
print(gapminder.head(5))

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [35]:
print(gapminder['continent'])

0         Asia
1         Asia
2         Asia
3         Asia
4         Asia
         ...
1699    Africa
1700    Africa
1701    Africa
1702    Africa
1703    Africa
Name: continent, Length: 1704, dtype: str

In [39]:
print(gapminder[['continent', 'country']])

     continent      country
0         Asia  Afghanistan
1         Asia  Afghanistan
2         Asia  Afghanistan
3         Asia  Afghanistan
4         Asia  Afghanistan
...        ...          ...
1699    Africa     Zimbabwe
1700    Africa     Zimbabwe
1701    Africa     Zimbabwe
1702    Africa     Zimbabwe
1703    Africa     Zimbabwe

[1704 rows x 2 columns]

In [43]:
print((gapminder['year'] >= 1980))
filtered_gapminder = gapminder[(gapminder['year'] >= 1980) & (gapminder['year'] <= 2000)]

filtered_gapminder

0       False
1       False
2       False
3       False
4       False
        ...
1699     True
1700     True
1701     True
1702     True
1703     True
Name: year, Length: 1704, dtype: bool

          country continent  year  lifeExp       pop    gdpPercap
6     Afghanistan      Asia  1982   39.854  12881816   978.011439
7     Afghanistan      Asia  1987   40.822  13867957   852.395945
8     Afghanistan      Asia  1992   41.674  16317921   649.341395
9     Afghanistan      Asia  1997   41.763  22227415   635.341351
18        Albania    Europe  1982   70.420   2780097  3630.880722
...           ...       ...   ...      ...       ...          ...
1689       Zambia    Africa  1997   40.238   9417789  1071.353818
1698     Zimbabwe    Africa  1982   60.363   7636524   788.855041
1699     Zimbabwe    Africa  1987   62.351   9216418   706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340   693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948   792.449960

[568 rows x 6 columns]